name: Deploy Hardhat to Devnet

on:
  pull_request:
    types: 
      - closed

jobs:
  deploy-and-build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DockerHub credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy Hardhat Contracts
        run: |
          cd hardhat
          npm install
          npx hardhat compile
          npx hardhat run scripts/deploy.js

      - name: Docker compose up
        run: |
          docker compose up -d --build
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: mtotovski/go-ethereum:contracts-deployed